services:
  - type: web
    name: optidevdoc
    env: node
    buildCommand: yarn install
    startCommand: node main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    plan: free
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 