services:
  - type: web
    name: optidevdoc
    env: node
    repo: https://github.com/biswajitpanday/OptiDevDoc.git
    buildCommand: yarn install && yarn build
    startCommand: node -r dotenv/config main.js
    plan: free
    region: oregon
    branch: master
    rootDir: .
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_TYPE
        value: sqlite
      - key: DATABASE_PATH
        value: ./data/optidevdoc.db
      - key: CACHE_ENABLED
        value: "true"
      - key: CACHE_TYPE
        value: memory
      - key: CACHE_TTL
        value: "3600"
      - key: CACHE_MAX_SIZE
        value: "1000"
      - key: LOG_FILE_ENABLED
        value: "true"
      - key: LOG_FILE_PATH
        value: ./logs
      - key: LOG_FILE_MAX_SIZE
        value: 10m
      - key: LOG_FILE_MAX_FILES
        value: "5"
      - key: LOG_CONSOLE_ENABLED
        value: "true"
      - key: LOG_CONSOLE_COLORIZE
        value: "true"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: RATE_LIMIT_WINDOW_MS
        value: "60000"
      - key: MCP_MODE
        value: http
      - key: ENABLE_PRODUCT_DETECTION
        value: "true"
      - key: ENABLE_ENHANCED_RULES
        value: "true"
      - key: ENABLE_CORS
        value: "true"
      - key: DEBUG_MCP
        value: "false"
      - key: CRAWLER_ENABLED
        value: "true"
      - key: CRAWLER_INTERVAL_HOURS
        value: "24"
      - key: CRAWLER_MAX_CONCURRENCY
        value: "3"
      - key: OPTIDEVDOC_MULTI_PRODUCT
        value: "true"
      - key: OPTIDEVDOC_RULES_PATH
        value: ./rules
      - key: OPTIDEVDOC_MODE
        value: remote
      - key: OPTIDEVDOC_DEBUG
        value: "false"
      - key: REMOTE_SERVER
        sync: true
      - key: VERSION
        fromPackageJson: version
        
    # Health check configuration
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    
    # Disk configuration for SQLite database and rules
    disk:
      name: optidevdoc-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  # Optional PostgreSQL database for production (upgrade from free tier)
  - type: pserv
    name: optidevdoc-postgres
    env: postgresql
    plan: free
    ipAllowList: []  # Only allow internal connections
    disk:
      name: pg-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Optional Redis for enhanced caching (upgrade from free tier)
  - type: redis
    name: optidevdoc-redis
    ipAllowList: []  # Only allow internal connections
    plan: free
    maxmemoryPolicy: volatile-lru 