services:
  - type: web
    name: optix
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: optix
          property: port
      - key: OPTIX_MODE
        value: server
      - key: OPTIDEV_DEBUG
        value: false
    healthCheckPath: /health